"""Add delivery_date and delivery_address to Order

Revision ID: 29f861114eb2
Revises: c0f5d836ec68
Create Date: 2024-09-25 00:46:49.598789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29f861114eb2'
down_revision = 'c0f5d836ec68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_date', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('delivery_address', sa.String(length=200), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('delivery_address')
        batch_op.drop_column('delivery_date')

    # ### end Alembic commands ###
